### ISSUE TITLE
Early game difficulty

### ISSUE THREAD

**Issue by SirFancyBacon** [hellbringer616/Strix_RPG#1]
Early game is nearly impossible due to enemy scaling and bloodmoon.

Possible Solution: ~~Add Mo' Mobs (if supported) and~~ adjust enemy scaling to create a smoother curve at early game; ramp up should be saved for the Nether; this can be implemented by:

1.) ~~Adjusting Mob HP values (File: MobHealth.properties)~~
2.) Adjusting mob Damage values [MobSettings.conf](https://github.com/hellbringer616/Strix_RPG/blob/master/MobSettings.conf)

Update: Only damage needs to be corrected; than balance can be verified.

**Comment by SirFancyBacon** [comment]
Commit 002396 added support for Mo'Creatures, Twilight Forest, and Abyss craft to the game; Mob scaling is now 12 types of broken; but i am hoping this has been refined a bit 

Definitely could use a hand squaring this away while i work on implementing the new gear.

**Comment by SirFancyBacon** [comment]
Improved with #5 and #6 testing is needed.

**Comment by SirFancyBacon** [comment]
Due to commit d34b5374e7641fba9327a3b26d176ab20003df8c all settings must be reconfigured; this was required to fix an XP bug

**Comment by SirFancyBacon** [comment]
Correct HP issue from previous comment with 55f214f544a222126a1ef79535b70c3cb6028fed

all that is left is damage.

**Comment by hellbringer616** [comment]
[NOTE]: Other worlds XP gain does not function; nearly sure it's a coding error on my part.

**Comment by SirFancyBacon** [comment]
MoCreatures and Vanilla creatures are complete got main overworld;

Additional balance may be needed

**Comment by SirFancyBacon** [comment]
Closing to recreate new issue
